#!/bin/bash

# =============================================================================
# generate-fl-clients.sh - Generate All 15 FL Client Pod Manifests
# =============================================================================
# This script generates YAML manifests for all 15 FL clients (cities 0-14)
# automatically, avoiding manual duplication.
#
# Usage:
#   bash generate-fl-clients.sh > fl-clients-generated.yaml
#   kubectl apply -f fl-clients-generated.yaml
#
# Or directly apply:
#   bash generate-fl-clients.sh | kubectl apply -f -
# =============================================================================

set -e

# City data: CITY_ID, City Name (lowercase), City Name (proper)
declare -A CITIES=(
    [0]="Berlin"
    [1]="Cairo"
    [2]="Dammam"
    [3]="Doha"
    [4]="Dubai"
    [5]="Jeddah"
    [6]="London"
    [7]="Mumbai"
    [8]="New York"
    [9]="Paris"
    [10]="Riyadh"
    [11]="Singapore"
    [12]="Sydney"
    [13]="Tokyo"
    [14]="Toronto"
)

# Convert city names to lowercase for DNS/pod naming
declare -A CITIES_LOWER=(
    [0]="berlin"
    [1]="cairo"
    [2]="dammam"
    [3]="doha"
    [4]="dubai"
    [5]="jeddah"
    [6]="london"
    [7]="mumbai"
    [8]="new-york"
    [9]="paris"
    [10]="riyadh"
    [11]="singapore"
    [12]="sydney"
    [13]="tokyo"
    [14]="toronto"
)

# Function to generate a single client pod
generate_client_pod() {
    local city_id=$1
    local city_name=$2
    local city_name_lower=$3
    
    cat <<EOF
---
# =============================================================================
# CLIENT $city_id: $city_name
# =============================================================================
apiVersion: v1
kind: Pod
metadata:
  name: fl-client-$city_id-$city_name_lower
  namespace: flower-fl
  labels:
    app: flower
    component: client
    city-id: "$city_id"
    city-name: $city_name_lower
    version: v1
  annotations:
    city: "$city_name"
    dataset: "weather_${city_name_lower}"
    description: "FL Client for $city_name (ID: $city_id)"
spec:
  serviceAccountName: fl-client
  restartPolicy: OnFailure
  
  # Init container: Wait for server to be ready
  initContainers:
    - name: wait-for-server
      image: busybox:1.28
      command: ['sh', '-c']
      args:
        - |
          echo "[$city_id] Waiting for FL server to be ready..."
          max_attempts=60
          attempt=0
          while [ \$attempt -lt \$max_attempts ]; do
            if nc -z fl-server.flower-fl.svc.cluster.local 8080 2>/dev/null; then
              echo "[$city_id] ✓ Server is ready!"
              exit 0
            fi
            attempt=\$((attempt + 1))
            echo "[$city_id] Attempt \$attempt/\$max_attempts..."
            sleep 2
          done
          echo "[$city_id] ✗ Server failed to become ready"
          exit 1
  
  # Containers
  containers:
    - name: client
      image: fl-weather-client:latest
      imagePullPolicy: IfNotPresent
      
      # Environment variables
      env:
        - name: CITY_ID
          value: "$city_id"
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: fl-client-config
              key: SERVER_ADDRESS
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: fl-client-config
              key: LOG_LEVEL
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: fl-client-config
              key: PYTHONUNBUFFERED
        - name: PYTHONDONTWRITEBYTECODE
          valueFrom:
            configMapKeyRef:
              name: fl-client-config
              key: PYTHONDONTWRITEBYTECODE
      
      # Resource limits (CRITICAL: strict per-pod limits)
      resources:
        requests:
          cpu: 250m          # 0.25 CPU
          memory: 400Mi      # 400MB
        limits:
          cpu: 500m          # 0.5 CPU
          memory: 750Mi      # 750MB
      
      # Volume mounts
      volumeMounts:
        - name: data
          mountPath: /app/data/processed
          readOnly: true
        - name: logs
          mountPath: /app/logs
          readOnly: false
      
      # Security context
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
            - ALL
  
  # Volumes
  volumes:
    - name: data
      emptyDir: {}
    - name: logs
      emptyDir: {}

EOF
}

# Output header
cat <<'EOF'
# =============================================================================
# FL-CLIENTS: Auto-Generated Manifest for All 15 Federated Learning Clients
# =============================================================================
# Generated by: generate-fl-clients.sh
# Cities: 0 (Berlin) to 14 (Toronto)
# Total Memory: ~10.5GB (0.5 CPU + 750Mi per pod × 15)
# =============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: flower-fl
  labels:
    name: flower-fl

---
# ConfigMap: Client Configuration (Shared)
apiVersion: v1
kind: ConfigMap
metadata:
  name: fl-client-config
  namespace: flower-fl
data:
  SERVER_ADDRESS: "fl-server.flower-fl.svc.cluster.local:8080"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

EOF

# Generate all 15 client pods
for city_id in {0..14}; do
    generate_client_pod "$city_id" "${CITIES[$city_id]}" "${CITIES_LOWER[$city_id]}"
done

# Output ServiceAccount and RBAC
cat <<'EOF'

---
# =============================================================================
# ServiceAccount: Client Pod Identity
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fl-client
  namespace: flower-fl
  labels:
    app: flower
    component: client

---
# =============================================================================
# Role: Client Permissions
# =============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fl-client
  namespace: flower-fl
  labels:
    app: flower
    component: client
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
# =============================================================================
# RoleBinding: Bind Role to ServiceAccount
# =============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fl-client
  namespace: flower-fl
  labels:
    app: flower
    component: client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fl-client
subjects:
  - kind: ServiceAccount
    name: fl-client
    namespace: flower-fl

# =============================================================================
# EOF
# =============================================================================
EOF
